### ISSUE TITLE
Able to add Header

### ISSUE THREAD

**Issue by ygorcesar** [huajianjiang/ExpandableRecyclerView#1]
Hello man, your library is very great!!!

I',m think, you can make getItem(position) public to be able override, because i need override this method =/
example:
getItem(position - 1) and getItemCount(size + 1); to include the header on RecyclerView, you can change this? or anyone solution? Sorry my poor english.

**Comment by progratient** [comment]
@ygorcesar 
Hi, friend, thank you  for support and issue.

I understand your issue, firstly because  `getItem(poisition)` return  `ItemWrapper<P,C>`  which is used by library privately , if want to get your parent/child item,  you don't have to override `getItem(position)`, you can call `ExpandableAdapter#getParent(position)/getChild(parentPosition,childPosition)` .

 Also . because library use your passed data to init inner data as you extend `ExpandableAdapter` and need to pass your data to it, if you override `ExpandableAdapter` 's `getItemCount()` and not return the real data size, `ExpandableAdapter` can not determine the itemType in `getItemViewType(position)` method, as well as can not  determine to which  `ViewHolder(parent/child)`  need to create in `ExpandableAdapter`'s  `onCreateViewHolder`  method.

So, if you need to add a header or/and footer , there are many ways you can do this: 
1. you can make your all  header/footer and other parent model class  implement library's `Parent` interface, and you can override `getParentType(parentPosition)` and use parentPosition and parent model class (header or other parent which implement `Parent`)  to determine the parent type.

2. if you need multiple or/and different type of header or/and footer , you can check this [HeaderAdapter](https://github.com/huajianjiang/BaseRecyclerView/blob/master/baserecyclerview/src/main/java/com/github/huajianjiang/baserecyclerview/adapter/HeaderAdapter.java)
